In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import os
from sqlalchemy import create_engine

In [2]:
folder_path='C:/Users/HP/Downloads/blinkit_sales_data'

In [3]:
file=[f for f in os.listdir('C:/Users/HP/Downloads/blinkit_sales_data')if f.lower().endswith(('.xls','.xlsx','.xlsm','.xlsb'))]

In [4]:
import os
import pandas as pd

folder = 'C:/Users/HP/Downloads/blinkit_sales_data'

files_to_convert = ['Category_Icons.xlsx', 'Rating_Icon.xlsx']

for f in files_to_convert:
    file_path = os.path.join(folder, f)
    
    df = pd.read_excel('C:/Users/HP/Downloads/blinkit_sales_data/Category_Icons.xlsx')
    
    new_name = f.replace('.xlsx', '.csv')
    new_path = os.path.join(folder, new_name)
    
    df.to_csv(new_path, index=False)
    
    print(f"Converted: {f} → {new_name}")

Converted: Category_Icons.xlsx → Category_Icons.csv
Converted: Rating_Icon.xlsx → Rating_Icon.csv

In [5]:
blinkit_customers=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_customers.csv')
blinkit_cust_feedback=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_customer_feedback.csv')
blinkit_delivery_perfo=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_delivery_performance.csv')
blinkit_inventory=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_inventory.csv')
blinkit_inventory_new=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_inventoryNew.csv')
blinkit_marketing_perfo=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_marketing_performance.csv')
blinkit_orders=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_orders.csv')
blinkit_order_items=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_order_items.csv')
blinkit_products=pd.read_csv('C:/Users/HP/Downloads/blinkit_sales_data/blinkit_products.csv')

blinkit customer

In [6]:
blinkit_customers['registration_date']=pd.to_datetime(blinkit_customers['registration_date'])
blinkit_customers['phone']=blinkit_customers['phone'].astype(str)
blinkit_customers['customer_name']=blinkit_customers['customer_name'].astype(str)
blinkit_customers['customer_segment']=blinkit_customers['customer_segment'].astype('category')

In [7]:
# phone flag 
blinkit_customers['phone_clean'] = (blinkit_customers['phone'].astype(str)
                    .str.replace(r'\D', '', regex=True))
blinkit_customers['phone_flag'] = blinkit_customers['phone_clean'].str.len() != 10

In [8]:
blinkit_customers['pincode']=blinkit_customers['pincode'].astype('str').str.replace(r'\.0$','',regex=True).str.strip()

In [9]:
blinkit_customers[blinkit_customers['pincode'].str.len()!=6].value_counts().sum()

np.int64(223)

pincode length fiil with 0 using zfill function

In [10]:
fill=blinkit_customers['pincode'].str.fullmatch(r'\d+',na=False)
blinkit_customers.loc[fill,'pincode']=(
    blinkit_customers.loc[fill,'pincode'].str.zfill(6)
)

In [11]:
blinkit_customers['pincode'].head(10)

0    321865
1    149394
2    621411
3    826054
4    730539
5    883122
6    649817
7    332997
8    528426
9    004515
Name: pincode, dtype: str

In [155]:
blinkit_customers

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,phone_clean,phone_flag,email_flag,pincode_flag
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,912987579691,True,False,False
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48,915123179717,True,False,False
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81,910034076149,True,False,False
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09,916264232390,True,False,False
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14,917293526596,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,48002829,Daksh Mandal,varkeymohammed@example.com,919587731286,"28/42, Venkataraman Ganj, Kishanganj-360157",Mumbai,045238,2024-01-25,Inactive,17,754.33,919587731286,True,False,False
2496,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81,916137420258,True,False,False
2497,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,1541.22,917595275963,True,False,False
2498,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,1185.50,911994009448,True,False,False
2499,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,376.50,914320353753,True,False,False

In [13]:
# email flag
blinkit_customers['email_flag']=blinkit_customers['email'].duplicated(keep=False)
# pincode flag
blinkit_customers['pincode_flag']=blinkit_customers['pincode'].fillna('').astype(str).str.replace('.0','',regex=False).str.len()!=6
blinkit_customers.loc[blinkit_customers['pincode_flag'],'pincode']=None

In [14]:
blinkit_customers['registration_date'].dt.year.value_counts()

registration_date
2024    1337
2023    1163
Name: count, dtype: int64

in blinkit customers customer_id add 0 using str.zfill()

In [15]:
# using zfill() add 0 on left side
blinkit_customers['customer_id']=(
    blinkit_customers['customer_id'].astype(str).str.zfill(8)
)

blinkit orders

In [16]:
blinkit_orders.sample(5)

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
3962,9408428,31456752,2023-08-30 13:34:14,2023-08-30 13:54:14,2023-08-30 13:50:14,On Time,1911.86,UPI,76392,9889
3319,5271947935,1601161,2024-08-26 23:07:11,2024-08-26 23:22:11,2024-08-26 23:18:11,On Time,1112.24,Wallet,70987,3959
2810,5263181887,90150193,2024-09-28 22:00:44,2024-09-28 22:13:44,2024-09-28 22:18:44,On Time,1239.90,Card,28643,2272
2120,493514666,12141418,2023-11-20 23:03:29,2023-11-20 23:17:29,2023-11-20 23:23:29,Slightly Delayed,1421.52,Wallet,5754,1953
2117,2106943908,27604184,2024-01-28 16:53:04,2024-01-28 17:03:04,2024-01-28 17:00:04,On Time,1032.40,Cash,33162,8901

In [17]:
blinkit_orders['customer_id']=(blinkit_orders['customer_id'].astype(str).str.zfill(8))

In [18]:
#convert float value into int value using round function 
blinkit_orders['order_total']=blinkit_orders['order_total'].round(0).astype(int)

In [19]:
blinkit_orders['order_date']=pd.to_datetime(blinkit_orders['order_date'],errors='coerce')

In [20]:
for col in ['order_date', 'promised_delivery_time', 'actual_delivery_time']:
    blinkit_orders[col] = pd.to_datetime(blinkit_orders[col], errors='coerce')
print(blinkit_orders[['order_date','promised_delivery_time',
                      'actual_delivery_time']].isna().sum())

order_date                0
promised_delivery_time    0
actual_delivery_time      0
dtype: int64

In [53]:
blinkit_orders.duplicated().sum()

np.int64(0)

In [54]:
blinkit_orders[blinkit_orders['order_id']=='1961864118']

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,delay_minutes,new_delivery_status
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197,Cash,63230,4771,-5.0,On Time

In [24]:
blinkit_orders['promised_delivery_time']=pd.to_datetime(blinkit_orders['promised_delivery_time'])
blinkit_orders['actual_delivery_time']=pd.to_datetime(blinkit_orders['actual_delivery_time'])
blinkit_orders['order_id']=blinkit_orders['order_id'].astype(str)

In [25]:
#calculate delay minutes
blinkit_orders['delay_minutes']=( blinkit_orders['actual_delivery_time']-blinkit_orders['promised_delivery_time']).dt.total_seconds()/60

In [26]:
def check_status(x):
    if x<=5:
        return 'On Time'
    elif x<=15:
        return 'Slightly Delayed'
    else:
        return 'Significantly Delayed'
    

blinkit_orders['new_delivery_status']=(blinkit_orders['delay_minutes'].apply(check_status))

blinkit products

In [69]:
blinkit_products.head()

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,948,1264,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127,170,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212,283,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,210,279,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",355,473,25.0,3,27,55

In [28]:
blinkit_products['product_id']=blinkit_products['product_id'].astype(str)

In [29]:
blinkit_products[blinkit_products['product_id']=='642612']

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
236,642612,Pet Treats,Pet Care,Pillay-Ahuja,517.03,795.43,35.0,365,16,57

In [30]:
blinkit_products[['price','mrp']]=blinkit_products[['price','mrp']].round(0).astype(int)

In [31]:
blinkit_products[blinkit_products['product_id']=='153019']

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,948,1264,25.0,3,13,88

blinkit order items

In [52]:
blinkit_order_items[blinkit_order_items['order_id']=='1961864118']

     order_id product_id  quantity  unit_price  item_total
0  1961864118     642612         3         517        1551

In [58]:
blinkit_orders[blinkit_orders['order_id']=='9644738826']

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,delay_minutes,new_delivery_status
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440,Card,61497,7917,-1.0,On Time

In [50]:
blinkit_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   str
 1   product_id  5000 non-null   str
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   int64
 4   item_total  5000 non-null   int64
dtypes: int64(3), str(2)
memory usage: 195.4 KB

In [68]:
blinkit_order_items[blinkit_order_items['order_id']=='9644738826']

     order_id product_id  quantity  unit_price  item_total
3  9644738826     561860         1         875         875

In [66]:
blinkit_order_items['order_id']=blinkit_order_items['order_id'].astype(str)
blinkit_order_items['product_id']=blinkit_order_items['product_id'].astype(str)
blinkit_order_items['unit_price']=blinkit_order_items['unit_price'].round(0).astype(int)
blinkit_order_items['item_total']=blinkit_order_items['item_total'].round(0).astype(int)

In [35]:
blinkit_order_items['item_total']=blinkit_order_items['quantity']*blinkit_order_items['unit_price']

orders final table

In [75]:
orders_final=blinkit_orders.merge(blinkit_order_items[['order_id','product_id','quantity','unit_price','item_total']],on='order_id',how='left')
orders_final

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,delay_minutes,new_delivery_status,product_id,quantity,unit_price,item_total
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197,Cash,63230,4771,-5.0,On Time,642612,3,517,1551
1,1549769649,09573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,977,Cash,14983,7534,2.0,On Time,378676,1,881,881
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839,UPI,39859,9886,4.0,On Time,741341,2,924,1848
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440,Card,61497,7917,-1.0,On Time,561860,1,875,875
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2527,Cash,84315,2741,1.0,On Time,602241,2,977,1953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132,Cash,90914,1587,5.0,On Time,925482,3,475,1425
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372,Cash,27952,3458,-2.0,On Time,124290,2,40,79
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158,Cash,9590,7424,3.0,On Time,491314,3,973,2920
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1919,UPI,29940,6128,-2.0,On Time,319388,2,658,1316
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879,Card,32851,5588,1.0,On Time,136533,1,826,826

In [76]:
orders_final['revenue']=orders_final['item_total']

In [81]:
orders_final=orders_final.drop(columns=['order_total_original'])

In [91]:
orders_final.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,payment_method,delivery_partner_id,store_id,delay_minutes,delivery_status,product_id,quantity,unit_price,revenue
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,Cash,63230,4771,-5.0,On Time,642612,3,517,1551
1,1549769649,09573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,Cash,14983,7534,2.0,On Time,378676,1,881,881
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,UPI,39859,9886,4.0,On Time,741341,2,924,1848
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,Card,61497,7917,-1.0,On Time,561860,1,875,875
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,Cash,84315,2741,1.0,On Time,602241,2,977,1953

In [95]:
orders_final[orders_final['order_id']=='5427684290']

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,payment_method,delivery_partner_id,store_id,delay_minutes,delivery_status,product_id,quantity,unit_price,revenue
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,Cash,84315,2741,1.0,On Time,602241,2,977,1953

blinkit products

In [93]:
blinkit_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    str
 1   product_name       268 non-null    str
 2   category           268 non-null    str
 3   brand              268 non-null    str
 4   price              268 non-null    int64
 5   mrp                268 non-null    int64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(1), int64(5), str(4)
memory usage: 21.1 KB

In [96]:
blinkit_products[blinkit_products['product_id']=='602241']

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
75,602241,Nuts,Snacks & Munchies,Bahl-Pau,977,1502,35.0,90,12,75

In [98]:
orders_final['product_id'] = orders_final['product_id'].astype(str)

orders_final = orders_final.merge(
    blinkit_products[['product_id', 'product_name', 'category', 'brand', 'margin_percentage']],
    on='product_id', how='left'
)

print(len(orders_final))                       # 5000
print(orders_final['category'].isna().sum())   # 0

5000
0

In [86]:
orders_final=orders_final.rename(columns={'order_total':'order_total_original'})
orders_final=orders_final.rename(columns={'new_delivery_status':'delivery_status'})

In [88]:
orders_final=orders_final.drop(columns=['item_total'])

In [84]:
orders_final=orders_final.drop(columns=['delivery_status'])

In [104]:
orders_final

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,payment_method,delivery_partner_id,store_id,delay_minutes,delivery_status,product_id,quantity,unit_price,revenue,product_name,category,brand,margin_percentage
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,Cash,63230,4771,-5.0,On Time,642612,3,517,1551,Pet Treats,Pet Care,Pillay-Ahuja,35.0
1,1549769649,09573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,Cash,14983,7534,2.0,On Time,378676,1,881,881,Orange Juice,Cold Drinks & Juices,Baral-Kamdar,30.0
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,UPI,39859,9886,4.0,On Time,741341,2,924,1848,Eggs,Dairy & Breakfast,Prasad LLC,20.0
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,Card,61497,7917,-1.0,On Time,561860,1,875,875,Orange Juice,Cold Drinks & Juices,Gupta Ltd,30.0
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,Cash,84315,2741,1.0,On Time,602241,2,977,1953,Nuts,Snacks & Munchies,Bahl-Pau,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,Cash,90914,1587,5.0,On Time,925482,3,475,1425,Frozen Biryani,Instant & Frozen Food,Viswanathan-Sha,40.0
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,Cash,27952,3458,-2.0,On Time,124290,2,40,79,Lotion,Personal Care,Sachdev Group,35.0
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,Cash,9590,7424,3.0,On Time,491314,3,973,2920,Ice Cream,Instant & Frozen Food,Banerjee Inc,40.0
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,UPI,29940,6128,-2.0,On Time,319388,2,658,1316,Orange Juice,Cold Drinks & Juices,D’Alia-Dey,30.0
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,Card,32851,5588,1.0,On Time,136533,1,826,826,Eggs,Dairy & Breakfast,"Raghavan, Magar and Shanker",20.0

In [105]:
basket = blinkit_order_items.groupby('order_id').agg(
    different_products=('product_id', 'nunique'),
    total_units=('quantity', 'sum')
).reset_index()

# orders with more than one product
print(basket[basket['different_products'] > 1])

Empty DataFrame
Columns: [order_id, different_products, total_units]
Index: []

blinkit marketing perfomance

In [141]:
blinkit_marketing_perfo

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas,ctr_pct
0,548299,New User Discount,2024-11-05,New Users,App,3130,163,78,1432,4778,3.34,5.21
1,390914,Weekend Special,2024-11-05,All,App,3925,494,45,4506,6238,1.38,12.59
2,834385,Festival Offer,2024-11-05,All,Email,7012,370,78,4524,2621,0.58,5.28
3,241523,Flash Sale,2024-11-05,All,SMS,1115,579,86,3623,2955,0.82,51.93
4,595111,Membership Drive,2024-11-05,Premium,Email,7172,795,54,2889,8952,3.10,11.08
...,...,...,...,...,...,...,...,...,...,...,...,...
5395,381623,Membership Drive,2023-03-17,Premium,Email,8331,809,92,2363,3711,1.57,9.71
5396,493317,Category Promotion,2023-03-17,All,Social Media,5216,860,34,3923,7701,1.96,16.49
5397,879292,App Push Notification,2023-03-17,All,App,8480,734,20,1991,6650,3.34,8.66
5398,461129,Email Campaign,2023-03-17,Inactive,Email,3569,568,10,4246,5880,1.38,15.91
5399,282514,Referral Program,2023-03-17,All,Social Media,5967,439,78,1512,8322,5.50,7.36

In [130]:
blinkit_marketing_perfo['campaign_name'].value_counts()

campaign_name
New User Discount        600
Weekend Special          600
Festival Offer           600
Flash Sale               600
Membership Drive         600
Category Promotion       600
App Push Notification    600
Email Campaign           600
Referral Program         600
Name: count, dtype: int64

In [131]:
blinkit_marketing_perfo['target_audience'].value_counts()

target_audience
New Users    1356
Premium      1355
Inactive     1347
All          1342
Name: count, dtype: int64

In [140]:
campaign_audience = {
    'New User Discount':     'New Users',   # clearly for new customers
    'Membership Drive':      'Premium',     # loyalty / paid membership
    'Email Campaign':        'Inactive',    # re-engagement emails
    'Weekend Special':       'All',
    'Festival Offer':        'All',
    'Flash Sale':            'All',
    'Category Promotion':    'All',
    'App Push Notification': 'All',
    'Referral Program':      'All',
}

blinkit_marketing_perfo['target_audience'] = blinkit_marketing_perfo['campaign_name'].map(campaign_audience)

In [112]:
blinkit_marketing_perfo['campaign_id']=blinkit_marketing_perfo['campaign_id'].astype(str)
blinkit_marketing_perfo['date']=pd.to_datetime(blinkit_marketing_perfo['date'])
blinkit_marketing_perfo['spend']=blinkit_marketing_perfo['spend'].round(0).astype(int)
blinkit_marketing_perfo['revenue_generated']=blinkit_marketing_perfo['revenue_generated'].round(0).astype(int)

In [ ]:
# return on ad spend (roas)
blinkit_marketing_perfo['roas']=(blinkit_marketing_perfo['revenue_generated']/blinkit_marketing_perfo['spend']).round(2)

In [118]:
blinkit_marketing_perfo['ctr_pct']=(blinkit_marketing_perfo['clicks']/blinkit_marketing_perfo['impressions']*100).round(2)

In [142]:
blinkit_delivery_perfo.head()

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

In [152]:
blinkit_delivery_perfo.shape

(5000, 8)

In [154]:
blinkit_delivery_perfo.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   str
 1   delivery_partner_id    5000 non-null   str
 2   promised_time          5000 non-null   datetime64[us]
 3   actual_time            5000 non-null   datetime64[us]
 4   delivery_time_minutes  5000 non-null   int64
 5   distance_km            5000 non-null   float64
 6   delivery_status        5000 non-null   category
 7   reasons_if_delayed     3098 non-null   str
dtypes: category(1), datetime64[us](2), float64(1), int64(1), str(3)
memory usage: 278.5 KB

In [153]:
blinkit_delivery_perfo['order_id']=blinkit_delivery_perfo['order_id'].astype(str)
blinkit_delivery_perfo['delivery_partner_id']=blinkit_delivery_perfo['delivery_partner_id'].astype(str)
blinkit_delivery_perfo['promised_time']=pd.to_datetime(blinkit_delivery_perfo['promised_time'])
blinkit_delivery_perfo['actual_time']=pd.to_datetime(blinkit_delivery_perfo['actual_time'])
blinkit_delivery_perfo['delivery_time_minutes']=blinkit_delivery_perfo['delivery_time_minutes'].astype(int)
blinkit_delivery_perfo['delivery_status']=blinkit_delivery_perfo['delivery_status'].astype('category')

In [143]:
orders_final.head()

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,payment_method,delivery_partner_id,store_id,delay_minutes,delivery_status,product_id,quantity,unit_price,revenue,product_name,category,brand,margin_percentage
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,Cash,63230,4771,-5.0,On Time,642612,3,517,1551,Pet Treats,Pet Care,Pillay-Ahuja,35.0
1,1549769649,09573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,Cash,14983,7534,2.0,On Time,378676,1,881,881,Orange Juice,Cold Drinks & Juices,Baral-Kamdar,30.0
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,UPI,39859,9886,4.0,On Time,741341,2,924,1848,Eggs,Dairy & Breakfast,Prasad LLC,20.0
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,Card,61497,7917,-1.0,On Time,561860,1,875,875,Orange Juice,Cold Drinks & Juices,Gupta Ltd,30.0
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,Cash,84315,2741,1.0,On Time,602241,2,977,1953,Nuts,Snacks & Munchies,Bahl-Pau,35.0